import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Brand.bg,
  },
  // Ambient background orbs for tech vibe
  orbTopRight: {
    position: 'absolute',
    top: -180,
    right: -140,
    width: 400,
    height: 400,
    borderRadius: 200,
    backgroundColor: 'rgba(31,167,80,0.15)',
  },
  orbMidLeft: {
    position: 'absolute',
    top: 320,
    left: -180,
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: 'rgba(244,166,42,0.11)',
  },
  orbBottom: {
    position: 'absolute',
    right: -120,
    bottom: 200,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(45,156,219,0.09)',
  },
  scroll: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 160,
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 10,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    ...Typography.title,
    color: Brand.text,
    fontWeight: '800',
    fontSize: 28,
    letterSpacing: -0.8,
    lineHeight: 32,
  },
  subtitle: {
    ...Typography.body,
    fontSize: 13,
    color: Brand.textSecondary,
    marginTop: 2,
    fontWeight: '500',
  },
  refreshBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: Brand.border,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.soft,
  },
  modeSwitch: {
    flexDirection: 'row',
    padding: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: Radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    gap: 4,
    ...Shadows.soft,
  },
  modeOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: Radii.pill,
  },
  modeOptionActive: {
    backgroundColor: Brand.greenDeeper,
  },
  modeText: {
    ...Typography.body,
    fontSize: 13,
    fontWeight: '800',
    color: Brand.text,
    letterSpacing: -0.1,
  },
  modeTextActive: {
    color: '#FFFFFF',
  },
  errorBox: {
    backgroundColor: '#FDE7E7',
    borderRadius: Radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(228,88,88,0.2)',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  errorText: {
    ...Typography.caption,
    color: Brand.danger,
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  loadingBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: 10,
  },
  loadingText: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  chapterTitle: {
    ...Typography.subtitle,
    fontSize: 15,
    fontWeight: '800',
    color: Brand.text,
    letterSpacing: -0.2,
    marginBottom: -4,
    marginTop: 4,
    paddingHorizontal: 2,
  },
  emptyCard: {
    padding: 22,
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: Radii.xxl,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    ...Shadows.card,
  },
  emptyIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: Brand.mintSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    ...Typography.body,
    fontSize: 16,
    fontWeight: '800',
    color: Brand.text,
  },
  emptyText: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontSize: 12,
    textAlign: 'center',
    paddingHorizontal: 12,
  },
});
