import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  hydrationCard: {
    backgroundColor: Brand.card,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D9ECF9',
    padding: 16,
    gap: 12,
    overflow: 'hidden',
    ...Shadows.soft,
  },
  hydrationGlow: {
    position: 'absolute',
    top: -56,
    right: -34,
    width: 118,
    height: 118,
    borderRadius: 59,
    backgroundColor: 'rgba(45,156,219,0.08)',
  },
  loadingBox: {
    borderRadius: 18,
    backgroundColor: '#F4FAFE',
    borderWidth: 1,
    borderColor: '#D9ECF9',
    padding: 14,
  },
  loadingText: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  title: {
    ...Typography.caption,
    color: '#2D9CDB',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  settingsButton: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#D9ECF9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  valueCurrent: {
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '800',
    color: Brand.text,
  },
  valueGoal: {
    ...Typography.helper,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  trackShell: {
    height: 8,
    borderRadius: Radii.pill,
    overflow: 'hidden',
    backgroundColor: '#D8EDF9',
  },
  trackFill: {
    height: '100%',
    borderRadius: Radii.pill,
    backgroundColor: '#2D9CDB',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  waterBtn: {
    borderRadius: 14,
    borderWidth: 1,
  },
  waterBtnPrimary: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    backgroundColor: '#F7FCFF',
    borderColor: '#D9ECF9',
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  waterBtnSecondary: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
    backgroundColor: '#F7FCFF',
    borderColor: '#D9ECF9',
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  waterBtnPrimaryContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  waterBtnSecondaryContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  waterBtnIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  waterBtnIconWrapPositive: {
    backgroundColor: '#2D9CDB',
  },
  waterBtnIconWrapNegative: {
    backgroundColor: '#FFF4F6',
  },
  waterBtnTextBlock: {
    flex: 1,
    gap: 0,
  },
  waterBtnText: {
    fontWeight: '800',
  },
  waterBtnTextPrimary: {
    ...Typography.body,
    color: '#2D9CDB',
  },
  waterBtnTextPositive: {
    ...Typography.caption,
    color: '#2D9CDB',
    fontWeight: '800',
  },
  waterBtnTextNegative: {
    ...Typography.subtitle,
    color: Brand.danger,
  },
  waterBtnTextSecondary: {
    ...Typography.caption,
    color: Brand.danger,
    fontWeight: '800',
  },
  hydrationGoalModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  hydrationGoalModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(16, 35, 26, 0.30)',
  },
  hydrationGoalMenu: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9ECF9',
    padding: 18,
    gap: 14,
    ...Shadows.floating,
  },
  hydrationGoalMenuTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  hydrationGoalMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  hydrationGoalMenuCopy: {
    flex: 1,
    gap: 4,
  },
  hydrationGoalMenuHint: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  hydrationGoalValueBadge: {
    borderRadius: 18,
    backgroundColor: '#EAF6FD',
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 96,
  },
  hydrationGoalValue: {
    ...Typography.subtitle,
    color: '#2D9CDB',
    fontWeight: '800',
  },
  hydrationGoalValueLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  sliderWrap: {
    paddingVertical: 8,
    paddingHorizontal: 2,
  },
  sliderTrack: {
    height: 32,
    borderRadius: Radii.pill,
    backgroundColor: '#D8EDF9',
    borderWidth: 1,
    borderColor: '#CFE8F6',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  sliderFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: Radii.pill,
    backgroundColor: '#2D9CDB',
  },
  sliderThumb: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#2D9CDB',
    top: 1,
    ...Shadows.card,
  },
  hydrationGoalScale: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  hydrationGoalScaleLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  hydrationGoalScaleHint: {
    ...Typography.caption,
    color: Brand.textSecondary,
  },
  error: {
    ...Typography.body,
    color: Brand.danger,
  },
  disabled: {
    opacity: 0.45,
  },
  pressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
});
