import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Brand.bg,
  },
  backgroundOrbTop: {
    position: 'absolute',
    top: -180,
    right: -130,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: 'rgba(31,167,80,0.12)',
  },
  backgroundOrbMid: {
    position: 'absolute',
    top: 220,
    left: -140,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(244,166,42,0.09)',
  },
  backgroundOrbBottom: {
    position: 'absolute',
    right: -110,
    bottom: 40,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(45,156,219,0.07)',
  },
  scroll: {
    paddingHorizontal: 20,
    gap: 22,
  },
  metricsSection: {
    gap: 14,
  },
  actionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: Radii.xxl,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.10)',
    padding: 24,
    gap: 20,
    overflow: 'hidden',
    ...Shadows.floating,
  },
  actionGlow: {
    position: 'absolute',
    top: -80,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(31,167,80,0.10)',
  },
  actionGlowSecondary: {
    position: 'absolute',
    bottom: -70,
    left: -40,
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: 'rgba(244,166,42,0.09)',
  },
  actionTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  actionEyebrowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Brand.mintSoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Radii.pill,
  },
  actionEyebrow: {
    ...Typography.caption,
    color: Brand.greenDeeper,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  actionDateChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: Radii.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  actionDateText: {
    ...Typography.helper,
    color: Brand.greenDark,
    fontWeight: '700',
    fontSize: 13,
  },
  actionBody: {
    gap: 6,
  },
  actionTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  actionSupport: {
    ...Typography.helper,
    color: Brand.textSecondary,
    lineHeight: 20,
    fontSize: 15,
  },
  actionPrimaryButton: {
    minHeight: 60,
    borderRadius: 22,
    borderWidth: 0,
    backgroundColor: Brand.greenDark,
    paddingHorizontal: 18,
    justifyContent: 'center',
    ...Shadows.floating,
  },
  actionPrimaryButtonPressed: {
    backgroundColor: Brand.greenDeeper,
    transform: [{ scale: 0.98 }],
  },
  actionPrimaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  actionPrimaryButtonText: {
    ...Typography.body,
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 16,
    letterSpacing: 0.1,
  },
  actionSecondaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionSecondaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.12)',
    backgroundColor: '#F7FAF7',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionSecondaryButtonPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
    backgroundColor: Brand.mintSoft,
  },
  actionSecondaryIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionSecondaryButtonText: {
    ...Typography.helper,
    color: Brand.text,
    fontWeight: '700',
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 28,
    lineHeight: 32,
    color: Brand.text,
    fontWeight: '800',
  },
  sectionSub: {
    ...Typography.helper,
    color: Brand.textSecondary,
    lineHeight: 21,
  },
});
