import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  hero: {
    backgroundColor: '#F8FAFF',
    borderRadius: Radii.xl,
    borderWidth: 1,
    borderColor: '#DDE5F4',
    padding: 18,
    gap: 14,
    overflow: 'hidden',
    ...Shadows.card,
  },
  heroGlowTop: {
    position: 'absolute',
    top: -74,
    right: -46,
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: 'rgba(255,122,89,0.16)',
  },
  heroGlowBottom: {
    position: 'absolute',
    left: -34,
    bottom: -56,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(91,108,255,0.14)',
  },
  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 14,
  },
  heroCopy: {
    flex: 1,
    gap: 2,
  },
  heroTitle: {
    fontSize: 28,
    lineHeight: 32,
    color: Brand.text,
    fontWeight: '800',
  },
  heroBadge: {
    minWidth: 92,
    borderRadius: 22,
    backgroundColor: Brand.indigo,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 2,
    ...Shadows.card,
  },
  heroBadgeValue: {
    fontSize: 26,
    lineHeight: 28,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  heroBadgeLabel: {
    ...Typography.caption,
    color: 'rgba(255,255,255,0.82)',
    fontWeight: '700',
  },
  loadingBox: {
    borderRadius: 20,
    backgroundColor: Brand.card,
    padding: 16,
  },
  loadingText: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  calorieSpotlight: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 22,
    backgroundColor: Brand.card,
    padding: 16,
    ...Shadows.soft,
  },
  calorieSpotlightCopy: {
    flex: 1,
    gap: 4,
  },
  calorieSpotlightLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  calorieSpotlightRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
  },
  calorieSpotlightValue: {
    fontSize: 42,
    lineHeight: 44,
    fontWeight: '800',
    color: Brand.text,
  },
  calorieSpotlightUnit: {
    ...Typography.body,
    color: Brand.coral,
    fontWeight: '700',
    marginBottom: 4,
  },
  calorieSpotlightHint: {
    ...Typography.helper,
    color: Brand.text,
    fontWeight: '700',
  },
  calorieBadge: {
    width: 104,
    borderRadius: 22,
    backgroundColor: Brand.blueSoft,
    paddingHorizontal: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  calorieBadgeIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Brand.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calorieBadgeValue: {
    ...Typography.subtitle,
    color: Brand.indigo,
    fontWeight: '800',
    textAlign: 'center',
  },
  calorieBadgeLabel: {
    ...Typography.caption,
    color: Brand.indigo,
    fontWeight: '700',
    textAlign: 'center',
  },
  track: {
    height: 10,
    borderRadius: Radii.pill,
    overflow: 'hidden',
    backgroundColor: '#DCE3F7',
  },
  fill: {
    height: '100%',
    borderRadius: Radii.pill,
    backgroundColor: Brand.indigo,
  },
  macroSection: {
    gap: 8,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  sectionMiniTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  counter: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  macroCard: {
    borderRadius: 18,
    backgroundColor: Brand.card,
    borderWidth: 1,
    borderColor: '#E5EAF6',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    ...Shadows.card,
  },
  macroLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  macroDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  macroLabel: {
    ...Typography.helper,
    color: Brand.text,
    fontWeight: '700',
  },
  macroTarget: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  trackShell: {
    height: 8,
    borderRadius: Radii.pill,
    overflow: 'hidden',
  },
  trackFill: {
    height: '100%',
    borderRadius: Radii.pill,
  },
  emptyGoalState: {
    borderRadius: 22,
    backgroundColor: Brand.card,
    padding: 18,
    gap: 8,
  },
  emptyGoalTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  emptyGoalText: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  consumedMetricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  consumedMetricCard: {
    width: '47%',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 8,
  },
  consumedMetricLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  consumedMetricValue: {
    ...Typography.subtitle,
    fontWeight: '800',
  },
  mealSummarySection: {
    gap: 10,
  },
  mealSummaryGrid: {
    gap: 12,
  },
  mealSummaryCard: {
    borderRadius: 22,
    backgroundColor: Brand.card,
    padding: 16,
    gap: 10,
    ...Shadows.card,
  },
  mealSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mealSummaryIcon: {
    width: 38,
    height: 38,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mealSummaryCopy: {
    flex: 1,
    gap: 2,
  },
  mealSummaryLabel: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  mealSummaryCount: {
    ...Typography.caption,
    color: Brand.textSecondary,
  },
  mealSummaryCalories: {
    ...Typography.body,
    color: Brand.greenDark,
    fontWeight: '800',
  },
  mealSummaryMacroRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  mealSummaryMacroChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mealSummaryMacroLabel: {
    ...Typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  mealSummaryMacroValue: {
    ...Typography.caption,
    fontWeight: '800',
  },
  sectionSub: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  secondaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: Radii.pill,
    backgroundColor: Brand.card,
    paddingHorizontal: 15,
    paddingVertical: 11,
    ...Shadows.card,
  },
  secondaryChipText: {
    ...Typography.body,
    color: Brand.indigo,
    fontWeight: '700',
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  error: {
    ...Typography.body,
    color: Brand.danger,
  },
});
