import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Brand.bg,
  },
  backgroundOrbTop: {
    position: 'absolute',
    top: -166,
    right: -102,
    width: 296,
    height: 296,
    borderRadius: 148,
    backgroundColor: 'rgba(31,167,80,0.09)',
  },
  backgroundOrbMid: {
    position: 'absolute',
    top: 248,
    left: -110,
    width: 214,
    height: 214,
    borderRadius: 107,
    backgroundColor: 'rgba(255,122,89,0.06)',
  },
  backgroundOrbBottom: {
    position: 'absolute',
    right: -84,
    bottom: 56,
    width: 198,
    height: 198,
    borderRadius: 99,
    backgroundColor: 'rgba(31,167,80,0.05)',
  },
  scroll: {
    paddingHorizontal: 20,
    gap: 20,
  },
  metricsSection: {
    gap: 14,
  },
  actionCard: {
    backgroundColor: Brand.card,
    borderRadius: Radii.xxl,
    borderWidth: 1,
    borderColor: 'rgba(21,32,24,0.08)',
    padding: 24,
    gap: 18,
    overflow: 'hidden',
    ...Shadows.card,
  },
  actionGlow: {
    position: 'absolute',
    top: -66,
    right: -38,
    width: 156,
    height: 156,
    borderRadius: 78,
    backgroundColor: 'rgba(255,122,89,0.09)',
  },
  actionTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  actionEyebrow: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  actionDateChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: Radii.pill,
    backgroundColor: '#F7FBF8',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  actionDateText: {
    ...Typography.body,
    color: Brand.greenDark,
    fontWeight: '700',
  },
  actionBody: {
    gap: 8,
  },
  actionTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '800',
  },
  actionSupport: {
    ...Typography.helper,
    color: Brand.textSecondary,
    lineHeight: 19,
  },
  actionPrimaryButton: {
    minHeight: 60,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#189347',
    backgroundColor: Brand.green,
    paddingHorizontal: 18,
    justifyContent: 'center',
    ...Shadows.card,
  },
  actionPrimaryButtonPressed: {
    backgroundColor: Brand.greenDark,
    transform: [{ scale: 0.99 }],
  },
  actionPrimaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  actionPrimaryButtonText: {
    ...Typography.body,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  actionSecondaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionSecondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(21,32,24,0.08)',
    backgroundColor: '#FBFDFC',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionSecondaryButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  actionSecondaryButtonText: {
    ...Typography.helper,
    color: Brand.text,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 28,
    lineHeight: 32,
    color: Brand.text,
    fontWeight: '800',
  },
  sectionSub: {
    ...Typography.helper,
    color: Brand.textSecondary,
    lineHeight: 21,
  },
});
