import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  hero: {
    backgroundColor: '#FCFDFC',
    borderRadius: Radii.xxl,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    padding: 24,
    gap: 20,
    overflow: 'hidden',
    ...Shadows.card,
  },
  heroGlowTop: {
    position: 'absolute',
    top: -88,
    right: -60,
    width: 212,
    height: 212,
    borderRadius: 106,
    backgroundColor: 'rgba(31,167,80,0.10)',
  },
  heroGlowBottom: {
    position: 'absolute',
    left: -48,
    bottom: -70,
    width: 164,
    height: 164,
    borderRadius: 82,
    backgroundColor: 'rgba(255,122,89,0.05)',
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 14,
  },
  heroSectionLabel: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  goalAction: {
    borderRadius: Radii.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  goalActionText: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '800',
  },
  loadingBox: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(21,32,24,0.08)',
    padding: 16,
  },
  loadingText: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  heroMainRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 18,
  },
  calorieBlock: {
    flex: 1,
    gap: 8,
  },
  calorieLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  calorieValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
  },
  calorieValue: {
    fontSize: 58,
    lineHeight: 60,
    fontWeight: '800',
    color: Brand.text,
  },
  calorieUnit: {
    ...Typography.helper,
    color: Brand.textSecondary,
    fontWeight: '700',
    marginBottom: 8,
  },
  mealBadge: {
    minWidth: 90,
    borderRadius: 18,
    backgroundColor: '#FFF8F4',
    borderWidth: 1,
    borderColor: '#FFE6DE',
    paddingHorizontal: 13,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  mealBadgeValue: {
    fontSize: 28,
    lineHeight: 30,
    color: Brand.coral,
    fontWeight: '800',
    textAlign: 'center',
  },
  mealBadgeLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
    textAlign: 'center',
  },
  track: {
    height: 10,
    borderRadius: Radii.pill,
    overflow: 'hidden',
    backgroundColor: '#E8F3EA',
  },
  fill: {
    height: '100%',
    borderRadius: Radii.pill,
    backgroundColor: Brand.greenDark,
  },
  heroSecondaryText: {
    ...Typography.helper,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  macroSection: {
    gap: 10,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  sectionMiniTitle: {
    fontSize: 24,
    lineHeight: 28,
    color: Brand.text,
    fontWeight: '800',
  },
  counter: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  macroCard: {
    borderRadius: 20,
    backgroundColor: '#FCFEFC',
    borderWidth: 1,
    borderColor: '#E4EFE6',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  macroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  macroLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  macroDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  macroLabel: {
    ...Typography.helper,
    color: Brand.text,
    fontWeight: '700',
  },
  macroMetricWrap: {
    alignItems: 'flex-end',
    gap: 2,
  },
  macroConsumed: {
    ...Typography.subtitle,
    fontWeight: '800',
  },
  macroTarget: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  trackShell: {
    height: 9,
    borderRadius: Radii.pill,
    overflow: 'hidden',
  },
  trackFill: {
    height: '100%',
    borderRadius: Radii.pill,
  },
  emptyGoalState: {
    borderRadius: 24,
    backgroundColor: '#F4FAF5',
    borderWidth: 1,
    borderColor: '#DDEFE1',
    padding: 18,
    gap: 10,
  },
  emptyGoalTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  emptyGoalText: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  consumedMetricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  consumedMetricCard: {
    width: '47%',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  consumedMetricLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  consumedMetricValue: {
    ...Typography.subtitle,
    fontWeight: '800',
  },
  mealSummarySection: {
    gap: 12,
  },
  mealSummaryGrid: {
    gap: 12,
  },
  mealSummaryCard: {
    borderRadius: 24,
    backgroundColor: '#FCFEFC',
    borderWidth: 1,
    borderColor: Brand.borderSoft,
    padding: 16,
    gap: 12,
  },
  mealSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mealSummaryIcon: {
    width: 36,
    height: 36,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mealSummaryCopy: {
    flex: 1,
    gap: 2,
  },
  mealSummaryLabel: {
    ...Typography.body,
    color: Brand.text,
    fontWeight: '800',
  },
  mealSummaryCount: {
    ...Typography.caption,
    color: Brand.textSecondary,
  },
  mealSummaryCalories: {
    ...Typography.body,
    color: Brand.greenDark,
    fontWeight: '800',
  },
  mealSummaryMacroRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  mealSummaryMacroChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  mealSummaryMacroLabel: {
    ...Typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  mealSummaryMacroValue: {
    ...Typography.caption,
    fontWeight: '800',
  },
  sectionSub: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  error: {
    ...Typography.body,
    color: Brand.danger,
  },
});
