import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  hydrationCard: {
    backgroundColor: '#F2FAFD',
    borderRadius: Radii.xl,
    borderWidth: 1,
    borderColor: '#D8EEF6',
    padding: 18,
    gap: 16,
    overflow: 'hidden',
    ...Shadows.card,
  },
  hydrationGlowLarge: {
    position: 'absolute',
    top: -78,
    right: -36,
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: 'rgba(11,107,148,0.12)',
  },
  hydrationGlowSmall: {
    position: 'absolute',
    left: -30,
    bottom: -42,
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(123,196,127,0.10)',
  },
  hydrationHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  hydrationHeaderCopy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  hydrationHeaderText: {
    flex: 1,
    gap: 2,
  },
  hydrationIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#DDF1F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hydrationTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  hydrationHeaderHint: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  hydrationSettingsButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8EEF6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingBox: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 16,
  },
  loadingText: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  hydrationTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  hydrationMetricGroup: {
    flex: 1,
    gap: 4,
  },
  hydrationEyebrow: {
    ...Typography.caption,
    color: '#0B6B94',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    fontWeight: '800',
  },
  hydrationHeroValue: {
    fontSize: 40,
    lineHeight: 42,
    fontWeight: '800',
    color: Brand.text,
  },
  hydrationMetricHint: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  hydrationProgressColumn: {
    alignItems: 'flex-end',
    gap: 8,
  },
  hydrationProgressBadge: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8EEF6',
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    minWidth: 88,
  },
  hydrationProgressBadgeDone: {
    backgroundColor: '#E7F6EC',
    borderColor: '#D3EBD9',
  },
  hydrationProgressValue: {
    ...Typography.subtitle,
    color: '#0B6B94',
    fontWeight: '800',
  },
  hydrationProgressValueDone: {
    color: Brand.greenDark,
  },
  hydrationProgressLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  hydrationProgressLabelDone: {
    color: Brand.greenDark,
  },
  hydrationSummaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    backgroundColor: '#E9F7FB',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  hydrationSummaryChipDone: {
    backgroundColor: '#E7F6EC',
  },
  hydrationSummaryChipText: {
    ...Typography.caption,
    color: '#0B6B94',
    fontWeight: '800',
  },
  hydrationSummaryChipTextDone: {
    color: Brand.greenDark,
  },
  hydrationTrackShell: {
    height: 12,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#D7EFF7',
  },
  hydrationTrackFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#0B6B94',
  },
  hydrationStatusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D8EEF6',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  hydrationStatusCardDone: {
    backgroundColor: '#E7F6EC',
    borderColor: '#D3EBD9',
  },
  hydrationStatus: {
    ...Typography.body,
    color: Brand.textSecondary,
    flex: 1,
  },
  hydrationStatusDone: {
    color: Brand.greenDark,
  },
  hydrationActionsSection: {
    gap: 8,
  },
  hydrationSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  hydrationSectionTitle: {
    ...Typography.caption,
    color: Brand.text,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    fontWeight: '800',
  },
  hydrationSectionHint: {
    ...Typography.caption,
    color: Brand.textSecondary,
  },
  hydrationPrimaryActions: {
    flexDirection: 'row',
    gap: 8,
  },
  hydrationSecondaryActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  waterBtn: {
    borderRadius: 20,
    borderWidth: 1,
  },
  waterBtnPrimary: {
    flex: 1,
    minWidth: 0,
    minHeight: 68,
    backgroundColor: '#0B6B94',
    borderColor: '#0B6B94',
    paddingHorizontal: 14,
    paddingVertical: 14,
    justifyContent: 'center',
    ...Shadows.soft,
  },
  waterBtnSecondary: {
    flex: 1,
    minWidth: 120,
    minHeight: 50,
    backgroundColor: '#FFFFFF',
    borderColor: '#F3D5DB',
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: 'center',
  },
  waterBtnPrimaryContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  waterBtnSecondaryContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  waterBtnIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  waterBtnIconWrapPositive: {
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  waterBtnIconWrapNegative: {
    backgroundColor: '#FFF4F6',
  },
  waterBtnTextBlock: {
    flex: 1,
    gap: 0,
  },
  waterBtnText: {
    fontWeight: '800',
  },
  waterBtnTextPrimary: {
    ...Typography.body,
    color: '#FFFFFF',
  },
  waterBtnTextPositive: {
    ...Typography.body,
    color: '#0B6B94',
  },
  waterBtnTextNegative: {
    ...Typography.subtitle,
    color: Brand.danger,
  },
  waterBtnTextSecondary: {
    ...Typography.body,
    color: Brand.danger,
  },
  hydrationGoalModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  hydrationGoalModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(16, 35, 26, 0.30)',
  },
  hydrationGoalMenu: {
    borderRadius: 24,
    backgroundColor: '#F6FCFE',
    borderWidth: 1,
    borderColor: '#D8EEF6',
    padding: 18,
    gap: 14,
    ...Shadows.floating,
  },
  hydrationGoalMenuTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  hydrationGoalMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  hydrationGoalMenuCopy: {
    flex: 1,
    gap: 4,
  },
  hydrationGoalMenuHint: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  hydrationGoalValueBadge: {
    borderRadius: 18,
    backgroundColor: '#E9F7FB',
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 96,
  },
  hydrationGoalValue: {
    ...Typography.subtitle,
    color: '#0B6B94',
    fontWeight: '800',
  },
  hydrationGoalValueLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  sliderWrap: {
    paddingVertical: 8,
    paddingHorizontal: 2,
  },
  sliderTrack: {
    height: 32,
    borderRadius: 999,
    backgroundColor: '#D7EFF7',
    borderWidth: 1,
    borderColor: '#C7E5F0',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  sliderFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 999,
    backgroundColor: '#0B6B94',
  },
  sliderThumb: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#0B6B94',
    top: 1,
    ...Shadows.card,
  },
  hydrationGoalScale: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  hydrationGoalScaleLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  hydrationGoalScaleHint: {
    ...Typography.caption,
    color: Brand.textSecondary,
  },
  error: {
    ...Typography.body,
    color: Brand.danger,
  },
  disabled: {
    opacity: 0.45,
  },
  pressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
});
