import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  card: {
    backgroundColor: '#FCFDFC',
    borderRadius: Radii.xxl,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    padding: 22,
    gap: 18,
    overflow: 'hidden',
    ...Shadows.card,
  },
  glowTop: {
    position: 'absolute',
    top: -90,
    right: -54,
    width: 214,
    height: 214,
    borderRadius: 107,
    backgroundColor: 'rgba(31,167,80,0.10)',
  },
  glowBottom: {
    position: 'absolute',
    left: -54,
    bottom: -74,
    width: 168,
    height: 168,
    borderRadius: 84,
    backgroundColor: 'rgba(45,156,219,0.08)',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  headerCopy: {
    flex: 1,
    gap: 4,
  },
  eyebrow: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  title: {
    fontSize: 30,
    lineHeight: 34,
    color: Brand.text,
    fontWeight: '800',
    letterSpacing: -0.7,
  },
  headerSupport: {
    ...Typography.helper,
    color: Brand.textSecondary,
  },
  action: {
    alignSelf: 'flex-start',
    borderRadius: Radii.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  actionText: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '800',
  },
  nutritionPanel: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(21,32,24,0.08)',
    padding: 18,
    gap: 14,
  },
  nutritionTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 14,
  },
  calorieBlock: {
    flex: 1,
    gap: 8,
  },
  panelLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  calorieValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
  },
  calorieValue: {
    fontSize: 54,
    lineHeight: 56,
    color: Brand.text,
    fontWeight: '800',
  },
  calorieUnit: {
    ...Typography.helper,
    color: Brand.textSecondary,
    fontWeight: '700',
    marginBottom: 8,
  },
  nutritionBadges: {
    alignItems: 'stretch',
    gap: 10,
    minWidth: 96,
  },
  progressBadge: {
    borderRadius: 18,
    backgroundColor: '#EEF8F1',
    borderWidth: 1,
    borderColor: '#D6EBD9',
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
    gap: 2,
  },
  progressBadgeValue: {
    ...Typography.subtitle,
    color: Brand.greenDark,
    fontWeight: '800',
  },
  progressBadgeLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
    textAlign: 'center',
  },
  mealBadge: {
    borderRadius: 18,
    backgroundColor: '#FFF4ED',
    borderWidth: 1,
    borderColor: '#FFDCCE',
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
    gap: 2,
  },
  mealBadgeValue: {
    ...Typography.subtitle,
    color: Brand.coral,
    fontWeight: '800',
  },
  mealBadgeLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
    textAlign: 'center',
  },
  nutritionTrack: {
    height: 10,
    borderRadius: Radii.pill,
    overflow: 'hidden',
    backgroundColor: '#E8F3EA',
  },
  nutritionFill: {
    height: '100%',
    borderRadius: Radii.pill,
    backgroundColor: Brand.greenDark,
  },
  nutritionSummary: {
    ...Typography.body,
    color: Brand.text,
    fontWeight: '700',
  },
  nutritionSecondary: {
    ...Typography.helper,
    color: Brand.textSecondary,
  },
  macroSection: {
    gap: 10,
  },
  macroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  macroTitle: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  macroGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  macroCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 112,
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingVertical: 12,
    justifyContent: 'space-between',
    borderWidth: 1,
  },
  macroTop: {
    gap: 6,
  },
  macroLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  macroDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  macroLabel: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '800',
  },
  macroValue: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
    textAlign: 'center',
    alignSelf: 'stretch',
  },
  macroGoal: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
    textAlign: 'center',
    alignSelf: 'stretch',
  },
  macroTrack: {
    height: 7,
    borderRadius: Radii.pill,
    overflow: 'hidden',
  },
  macroTrackBase: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: Radii.pill,
  },
  macroFill: {
    height: '100%',
    borderRadius: Radii.pill,
  },
  hydrationPanel: {
    borderRadius: 24,
    backgroundColor: '#F3FAFF',
    borderWidth: 1,
    borderColor: '#D8ECF8',
    padding: 18,
    gap: 12,
  },
  hydrationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  hydrationLabel: {
    ...Typography.caption,
    color: Brand.hydration,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  hydrationBadge: {
    borderRadius: Radii.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8ECF8',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  hydrationBadgeText: {
    ...Typography.caption,
    color: Brand.hydration,
    fontWeight: '800',
  },
  hydrationValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  hydrationValue: {
    fontSize: 32,
    lineHeight: 36,
    color: Brand.text,
    fontWeight: '800',
  },
  hydrationGoal: {
    ...Typography.helper,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  hydrationTrack: {
    height: 8,
    borderRadius: Radii.pill,
    overflow: 'hidden',
    backgroundColor: '#D8EDF9',
  },
  hydrationFill: {
    height: '100%',
    borderRadius: Radii.pill,
    backgroundColor: Brand.hydration,
  },
  hydrationSupport: {
    ...Typography.helper,
    color: Brand.textSecondary,
    lineHeight: 20,
  },
  error: {
    ...Typography.body,
    color: Brand.danger,
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
});
