import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Brand.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(20,108,56,0.08)',
    backgroundColor: '#FFFFFF',
  },
  headerAction: {
    ...Typography.body,
    fontSize: 14,
    fontWeight: '700',
    color: Brand.textSecondary,
    letterSpacing: 0.1,
  },
  headerTitle: {
    ...Typography.subtitle,
    fontSize: 16,
    fontWeight: '900',
    color: Brand.text,
    letterSpacing: -0.3,
  },
  headerSpacer: {
    width: 52,
  },
  scroll: {
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 48,
    gap: 14,
  },
  avatarWrap: {
    alignSelf: 'center',
    position: 'relative',
    padding: 3,
    borderRadius: 60,
    backgroundColor: Brand.fresh,
    ...Shadows.card,
  },
  avatarImg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: Brand.bg,
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: Brand.forest,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: Brand.bg,
  },
  avatarLetter: {
    fontSize: 38,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -1,
  },
  avatarBadge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Brand.greenDeeper,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: Brand.bg,
  },
  avatarHint: {
    ...Typography.caption,
    fontSize: 11,
    color: Brand.textMuted,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    marginTop: 8,
  },
  messageBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
  },
  messageText: {
    ...Typography.body,
    fontSize: 13,
    flex: 1,
    fontWeight: '600',
  },
  errorBox: {
    backgroundColor: '#FFF0F0',
    borderColor: '#F2C6CB',
  },
  errorText: {
    color: Brand.danger,
  },
  successBox: {
    backgroundColor: '#F0FFF4',
    borderColor: '#C7E9D0',
  },
  successText: {
    color: Brand.greenDark,
  },
  sectionLabel: {
    ...Typography.caption,
    fontSize: 10,
    fontWeight: '900',
    color: Brand.textMuted,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    marginTop: 4,
    marginLeft: 4,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    ...Shadows.card,
  },
  infoCopy: {
    flex: 1,
    gap: 2,
  },
  infoHint: {
    ...Typography.caption,
    fontSize: 11,
    color: Brand.textMuted,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  actionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    ...Shadows.card,
  },
  cardPressed: {
    opacity: 0.96,
    transform: [{ scale: 0.99 }],
    backgroundColor: Brand.surfaceAlt,
  },
  actionIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionCopy: {
    flex: 1,
    gap: 2,
  },
  actionTitle: {
    ...Typography.body,
    fontSize: 15,
    fontWeight: '800',
    color: Brand.text,
    letterSpacing: -0.2,
  },
  actionDescription: {
    ...Typography.caption,
    fontSize: 11,
    color: Brand.textSecondary,
    fontWeight: '600',
    letterSpacing: 0.1,
  },
  utilityGroup: {
    gap: 10,
    marginTop: 2,
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: Radii.xl,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    gap: 14,
    ...Shadows.card,
  },
  sectionTitle: {
    ...Typography.subtitle,
    fontSize: 18,
    fontWeight: '900',
    color: Brand.text,
    letterSpacing: -0.3,
  },
  sectionSubtitle: {
    ...Typography.body,
    fontSize: 13,
    lineHeight: 18,
    color: Brand.textSecondary,
    fontWeight: '500',
  },
  currentInfo: {
    backgroundColor: Brand.surfaceSoft,
    borderRadius: 14,
    padding: 14,
    gap: 3,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
  },
  currentLabel: {
    ...Typography.caption,
    fontSize: 10,
    color: Brand.greenDark,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  currentValue: {
    ...Typography.body,
    fontSize: 16,
    fontWeight: '800',
    color: Brand.text,
    letterSpacing: -0.2,
  },
  fieldGroup: {
    gap: 6,
  },
  passwordInputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  passwordInput: {
    paddingRight: 52,
  },
  passwordToggle: {
    position: 'absolute',
    right: 14,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  passwordTogglePressed: {
    opacity: 0.72,
  },
  fieldLabel: {
    ...Typography.caption,
    fontSize: 11,
    fontWeight: '800',
    color: Brand.textSecondary,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginLeft: 4,
  },
  statusBox: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
  },
  statusText: {
    ...Typography.body,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  inlineHelper: {
    paddingHorizontal: 4,
  },
  inlineHelperText: {
    ...Typography.caption,
    fontSize: 12,
    color: Brand.textSecondary,
    lineHeight: 16,
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    marginTop: 10,
    borderRadius: Radii.pill,
    backgroundColor: '#FFF4F5',
    borderWidth: 1,
    borderColor: '#FCD5DB',
  },
  logoutText: {
    ...Typography.body,
    fontSize: 14,
    fontWeight: '800',
    color: Brand.danger,
    letterSpacing: 0.2,
  },
  ppOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  ppSheet: {
    backgroundColor: Brand.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingBottom: 42,
    paddingHorizontal: 18,
  },
  ppHandleWrap: {
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 14,
  },
  ppHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: Brand.border,
  },
  ppTitle: {
    ...Typography.body,
    fontSize: 15,
    fontWeight: '800',
    color: Brand.text,
    textAlign: 'center',
    marginBottom: 16,
  },
  ppActions: {
    backgroundColor: '#FFFFFF',
    borderRadius: Radii.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
  },
  ppBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 18,
    gap: 14,
  },
  ppBtnPressed: {
    backgroundColor: Brand.surfaceAlt,
  },
  ppBtnBorder: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Brand.border,
  },
  ppIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ppBtnLabel: {
    ...Typography.body,
    fontSize: 15,
    fontWeight: '700',
    color: Brand.text,
  },
  ppCancelBtn: {
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: Radii.pill,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Brand.border,
  },
  ppCancelText: {
    ...Typography.body,
    fontSize: 14,
    fontWeight: '800',
    color: Brand.textSecondary,
  },
});
