import { StyleSheet } from 'react-native';

import { Brand, Radii, Shadows, Typography } from '@/constants/theme';

export const s = StyleSheet.create({
  nutritionHeroCard: {
    backgroundColor: '#FCFDFC',
    borderRadius: Radii.xxl,
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    padding: 18,
    gap: 14,
    overflow: 'hidden',
    ...Shadows.card,
  },
  nutritionHeroGlowTop: {
    position: 'absolute',
    top: -90,
    right: -52,
    width: 196,
    height: 196,
    borderRadius: 98,
    backgroundColor: 'rgba(31,167,80,0.10)',
  },
  nutritionHeroGlowBottom: {
    position: 'absolute',
    left: -46,
    bottom: -64,
    width: 146,
    height: 146,
    borderRadius: 73,
    backgroundColor: 'rgba(45,156,219,0.08)',
  },
  nutritionHeroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  nutritionHeroCopy: {
    flex: 1,
    gap: 10,
  },
  nutritionHeroBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroEyebrowPill: {
    borderRadius: Radii.pill,
    backgroundColor: '#EAF6ED',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroEyebrowText: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  heroSourcePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: Radii.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroSourceText: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '700',
  },
  nutritionHeroTitle: {
    fontSize: 28,
    lineHeight: 32,
    color: Brand.text,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  nutritionHeroSubtitle: {
    ...Typography.body,
    color: Brand.textSecondary,
  },
  nutritionHeroPhoto: {
    width: 88,
    height: 88,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
  },
  nutritionHeroPhotoFallback: {
    width: 88,
    height: 88,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionHeroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  infoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  infoBadgeWarm: {
    backgroundColor: '#FFF9F0',
    borderColor: '#F3DFC0',
  },
  infoBadgeValue: {
    ...Typography.body,
    color: Brand.greenDark,
    fontWeight: '800',
  },
  infoBadgeValueWarm: {
    color: Brand.warning,
  },
  infoBadgeText: {
    ...Typography.caption,
    color: Brand.textSecondary,
    fontWeight: '700',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryMetricCard: {
    flexGrow: 1,
    flexBasis: '47%',
    minWidth: 140,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    padding: 14,
    gap: 12,
  },
  summaryMetricAccent: {
    alignSelf: 'flex-start',
    borderRadius: Radii.pill,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  summaryMetricAccentText: {
    ...Typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  summaryMetricValue: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  reviewCard: {
    backgroundColor: Brand.card,
    borderRadius: Radii.xl,
    borderWidth: 1,
    borderColor: Brand.border,
    padding: 18,
    gap: 14,
    ...Shadows.card,
  },
  card: {
    backgroundColor: Brand.card,
    borderRadius: Radii.xl,
    borderWidth: 1,
    borderColor: Brand.border,
    padding: 16,
    gap: 12,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionCopy: {
    flex: 1,
    gap: 4,
  },
  sectionTitle: {
    ...Typography.subtitle,
    color: Brand.text,
    fontWeight: '800',
  },
  sectionHint: {
    ...Typography.helper,
    color: Brand.textSecondary,
  },
  sectionCountBadge: {
    minWidth: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Brand.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  sectionCountText: {
    ...Typography.caption,
    color: Brand.greenDark,
    fontWeight: '800',
  },
  correctionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  correctionRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  correctionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    borderRadius: 16,
    backgroundColor: Brand.bg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  correctionFrom: {
    ...Typography.helper,
    color: Brand.textSecondary,
  },
  correctionArrow: {
    ...Typography.helper,
    color: Brand.textSecondary,
  },
  correctionTo: {
    ...Typography.helper,
    color: Brand.text,
    fontWeight: '800',
  },
  ingredientList: {
    gap: 10,
  },
  ingredientCard: {
    borderRadius: 20,
    backgroundColor: '#FBFDFC',
    borderWidth: 1,
    borderColor: Brand.border,
    padding: 14,
    gap: 10,
  },
  ingredientCardActive: {
    borderColor: '#B8D9C2',
    backgroundColor: '#F4FAF5',
  },
  ingredientCardPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.995 }],
  },
  ingredientHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  ingredientCopy: {
    flex: 1,
    gap: 4,
  },
  ingredientName: {
    ...Typography.body,
    color: Brand.text,
    fontWeight: '800',
  },
  ingredientMetaText: {
    ...Typography.caption,
    color: Brand.textSecondary,
  },
  ingredientHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ingredientAttentionText: {
    ...Typography.caption,
    color: Brand.warning,
    fontWeight: '700',
  },
  ingredientDetailsCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(20,108,56,0.08)',
    padding: 12,
    gap: 8,
  },
  ingredientWarningsList: {
    gap: 6,
  },
  ingredientWarningText: {
    ...Typography.caption,
    color: Brand.warning,
    lineHeight: 18,
  },
  ingredientFutureHint: {
    ...Typography.caption,
    color: Brand.textSecondary,
    lineHeight: 18,
  },
  statusPill: {
    borderRadius: Radii.pill,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillText: {
    ...Typography.caption,
    fontWeight: '800',
  },
  detectedList: {
    gap: 12,
  },
  detectedItem: {
    gap: 8,
    borderRadius: 16,
    backgroundColor: Brand.bg,
    padding: 14,
  },
  detectedItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detectedName: {
    ...Typography.body,
    fontWeight: '700',
    color: Brand.text,
  },
  detectedMacroRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  emptyInlineText: {
    ...Typography.helper,
    color: Brand.textSecondary,
  },
  manualToggleButton: {
    borderRadius: Radii.pill,
    backgroundColor: Brand.surfaceSoft,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  manualToggleText: {
    ...Typography.caption,
    fontWeight: '800',
    color: Brand.greenDark,
  },
  manualEditorBody: {
    gap: 12,
  },
  inputLabel: {
    ...Typography.caption,
    fontWeight: '700',
    color: Brand.text,
  },
  gridRow: {
    flexDirection: 'row',
    gap: 12,
  },
  gridCell: {
    flex: 1,
    gap: 6,
  },
  itemCard: {
    borderRadius: 16,
    backgroundColor: Brand.bg,
    padding: 14,
    gap: 10,
  },
  removeButton: {
    alignSelf: 'flex-start',
    borderRadius: Radii.pill,
    backgroundColor: '#FFF0F0',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  removeButtonText: {
    ...Typography.caption,
    fontWeight: '700',
    color: Brand.danger,
  },
  addButton: {
    alignSelf: 'flex-start',
    borderRadius: Radii.pill,
    backgroundColor: '#E7F6EC',
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  addButtonText: {
    ...Typography.caption,
    fontWeight: '700',
    color: Brand.greenDark,
  },
  manualHint: {
    ...Typography.helper,
    color: Brand.textSecondary,
  },
  multiInput: {
    minHeight: 130,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Brand.border,
    backgroundColor: Brand.bg,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: Brand.text,
    textAlignVertical: 'top',
  },
  readonlyInput: {
    opacity: 0.8,
  },
  macroChip: {
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 4,
  },
  macroChipCompact: {
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  macroChipLabel: {
    ...Typography.caption,
    fontWeight: '700',
  },
  macroChipValue: {
    ...Typography.caption,
    fontWeight: '800',
  },
});
